name: Go

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build linux
      run: |
        GOOS=linux GOARCH=amd64 go build -v -ldflags "-s -w" -o magneto
        tar -czvf magneto_linux_x86_64.tar.gz magneto
        rm magneto

    - name: Build windows
      run: |
        mkdir magneto
        GOOS=windows GOARCH=amd64 go build -v -ldflags "-s -w" -o magneto/magneto.exe
        cp scripts/* magneto/
        zip -r magneto_windows_x86_64.zip magneto/
        rm -rf magneto

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          magneto_linux_x86_64.tar.gz
          magneto_windows_x86_64.zip

